{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "pip install -r requirements.txt\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "! pip install --upgrade pip\n",
    "1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "! pip install dash==2.0.0\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "! pip install gevent"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "::1 - - [2025-04-08 16:02:59] \"GET / HTTP/1.1\" 200 1988 0.207715\n",
      "::1 - - [2025-04-08 16:02:59] \"GET / HTTP/1.1\" 200 1988 0.000497\n",
      "::1 - - [2025-04-08 16:02:59] \"GET /assets/styles.css?m=1744133337.9919899 HTTP/1.1\" 304 141 0.003653\n",
      "::1 - - [2025-04-08 16:02:59] \"GET /_dash-layout HTTP/1.1\" 200 2647 0.000939\n",
      "::1 - - [2025-04-08 16:02:59] \"GET /_dash-dependencies HTTP/1.1\" 200 1253 0.000203\n",
      "::1 - - [2025-04-08 16:02:59] \"GET /_dash-component-suites/dash/dcc/async-datepicker.js HTTP/1.1\" 304 66 0.000808\n",
      "::1 - - [2025-04-08 16:02:59] \"POST /_dash-update-component HTTP/1.1\" 200 387 0.000475\n",
      "::1 - - [2025-04-08 16:02:59] \"POST /_dash-update-component HTTP/1.1\" 200 168 0.000341\n",
      "::1 - - [2025-04-08 16:02:59] \"POST /_dash-update-component HTTP/1.1\" 200 166 0.000209\n",
      "::1 - - [2025-04-08 16:02:59] \"POST /_dash-update-component HTTP/1.1\" 200 170 0.000187\n",
      "::1 - - [2025-04-08 16:02:59] \"GET /assets/stocks-img.jpg HTTP/1.1\" 304 145 0.000372\n",
      "[2025-04-08 16:03:13,763] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/logankronforst/Desktop/stock-prediction-dash/app.py\", line 123, in update_data\n",
      "    inf = ticker.info\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/ticker.py\", line 142, in info\n",
      "    return self.get_info()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/base.py\", line 1678, in get_info\n",
      "    data = self._quote.info\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/scrapers/quote.py\", line 571, in info\n",
      "    self._fetch(self.proxy)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/scrapers/quote.py\", line 600, in _fetch\n",
      "    result = self._data.get_raw_json(\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/data.py\", line 75, in get_raw_json\n",
      "    response.raise_for_status()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/requests/models.py\", line 1021, in raise_for_status\n",
      "    raise HTTPError(http_error_msg, response=self)\n",
      "requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://query2.finance.yahoo.com/v6/finance/quoteSummary/TSLA?modules=financialData&modules=quoteType&modules=defaultKeyStatistics&modules=assetProfile&modules=summaryDetail&ssl=true\n",
      "::1 - - [2025-04-08 16:03:13] \"POST /_dash-update-component HTTP/1.1\" 500 426 0.162315\n",
      "[2025-04-08 16:03:15,692] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/logankronforst/Desktop/stock-prediction-dash/app.py\", line 123, in update_data\n",
      "    inf = ticker.info\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/ticker.py\", line 142, in info\n",
      "    return self.get_info()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/base.py\", line 1678, in get_info\n",
      "    data = self._quote.info\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/scrapers/quote.py\", line 571, in info\n",
      "    self._fetch(self.proxy)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/scrapers/quote.py\", line 600, in _fetch\n",
      "    result = self._data.get_raw_json(\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/data.py\", line 75, in get_raw_json\n",
      "    response.raise_for_status()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/requests/models.py\", line 1021, in raise_for_status\n",
      "    raise HTTPError(http_error_msg, response=self)\n",
      "requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://query2.finance.yahoo.com/v6/finance/quoteSummary/TSLA?modules=financialData&modules=quoteType&modules=defaultKeyStatistics&modules=assetProfile&modules=summaryDetail&ssl=true\n",
      "::1 - - [2025-04-08 16:03:15] \"POST /_dash-update-component HTTP/1.1\" 500 426 0.061312\n",
      "::1 - - [2025-04-08 16:03:22] \"POST /_dash-update-component HTTP/1.1\" 200 166 0.000844\n",
      "::1 - - [2025-04-08 16:03:22] \"POST /_dash-update-component HTTP/1.1\" 200 168 0.000431\n",
      "::1 - - [2025-04-08 16:03:26] \"POST /_dash-update-component HTTP/1.1\" 200 166 0.001920\n",
      "::1 - - [2025-04-08 16:03:26] \"POST /_dash-update-component HTTP/1.1\" 200 168 0.001073\n",
      "[2025-04-08 16:03:33,515] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/logankronforst/Desktop/stock-prediction-dash/app.py\", line 123, in update_data\n",
      "    inf = ticker.info\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/ticker.py\", line 142, in info\n",
      "    return self.get_info()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/base.py\", line 1678, in get_info\n",
      "    data = self._quote.info\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/scrapers/quote.py\", line 571, in info\n",
      "    self._fetch(self.proxy)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/scrapers/quote.py\", line 600, in _fetch\n",
      "    result = self._data.get_raw_json(\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/yfinance/data.py\", line 75, in get_raw_json\n",
      "    response.raise_for_status()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/requests/models.py\", line 1021, in raise_for_status\n",
      "    raise HTTPError(http_error_msg, response=self)\n",
      "requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://query2.finance.yahoo.com/v6/finance/quoteSummary/TSLA?modules=financialData&modules=quoteType&modules=defaultKeyStatistics&modules=assetProfile&modules=summaryDetail&ssl=true\n",
      "::1 - - [2025-04-08 16:03:33] \"POST /_dash-update-component HTTP/1.1\" 500 426 0.060766\n",
      "Failed to get ticker 'TSLA' reason: Expecting value: line 1 column 1 (char 0)\n",
      "[*********************100%%**********************]  1 of 1 completed\n",
      "\n",
      "1 Failed download:\n",
      "['TSLA']: Exception('%ticker%: No timezone found, symbol may be delisted')\n",
      "::1 - - [2025-04-08 16:03:39] \"POST /_dash-update-component HTTP/1.1\" 200 7382 0.375564\n",
      "::1 - - [2025-04-08 16:03:39] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 304 66 0.003516\n",
      "::1 - - [2025-04-08 16:03:39] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 304 66 0.000473\n",
      "Failed to get ticker 'TSLA' reason: Expecting value: line 1 column 1 (char 0)\n",
      "[*********************100%%**********************]  1 of 1 completed\n",
      "\n",
      "1 Failed download:\n",
      "['TSLA']: Exception('%ticker%: No timezone found, symbol may be delisted')\n",
      "::1 - - [2025-04-08 16:03:41] \"POST /_dash-update-component HTTP/1.1\" 200 7381 0.101445\n",
      "[2025-04-08 16:03:43,380] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/logankronforst/Desktop/stock-prediction-dash/app.py\", line 186, in forecast\n",
      "    fig = prediction(val, int(n_days) + 1)\n",
      "TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'\n",
      "::1 - - [2025-04-08 16:03:43] \"POST /_dash-update-component HTTP/1.1\" 500 426 0.002559\n",
      "/Users/logankronforst/Desktop/stock-prediction-dash/model.py:3: UserWarning:\n",
      "\n",
      "\n",
      "The dash_core_components package is deprecated. Please replace\n",
      "`import dash_core_components as dcc` with `from dash import dcc`\n",
      "\n",
      "/Users/logankronforst/Desktop/stock-prediction-dash/model.py:4: UserWarning:\n",
      "\n",
      "\n",
      "The dash_html_components package is deprecated. Please replace\n",
      "`import dash_html_components as html` with `from dash import html`\n",
      "\n",
      "Failed to get ticker 'TSLA' reason: Expecting value: line 1 column 1 (char 0)\n",
      "[*********************100%%**********************]  1 of 1 completed\n",
      "\n",
      "1 Failed download:\n",
      "['TSLA']: Exception('%ticker%: No price data found, symbol may be delisted (period=60d)')\n",
      "[2025-04-08 16:03:48,639] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 2077, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1525, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1523, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/flask/app.py\", line 1509, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/dash/dash.py\", line 1336, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/dash/_callback.py\", line 151, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/logankronforst/Desktop/stock-prediction-dash/app.py\", line 186, in forecast\n",
      "    fig = prediction(val, int(n_days) + 1)\n",
      "  File \"/Users/logankronforst/Desktop/stock-prediction-dash/model.py\", line 34, in prediction\n",
      "    x_train, x_test, y_train, y_test = train_test_split(X,\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/sklearn/utils/_param_validation.py\", line 213, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/sklearn/model_selection/_split.py\", line 2660, in train_test_split\n",
      "    n_train, n_test = _validate_shuffle_split(\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/sklearn/model_selection/_split.py\", line 2308, in _validate_shuffle_split\n",
      "    raise ValueError(\n",
      "ValueError: With n_samples=0, test_size=0.1 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.\n",
      "::1 - - [2025-04-08 16:03:48] \"POST /_dash-update-component HTTP/1.1\" 500 426 0.137932\n",
      "^C\n",
      "KeyboardInterrupt\n",
      "2025-04-08T22:10:14Z\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/logankronforst/Desktop/stock-prediction-dash/app.py\", line 193, in <module>\n",
      "    http_server.serve_forever()\n",
      "  File \"/Users/logankronforst/Library/Python/3.10/lib/python/site-packages/gevent/baseserver.py\", line 400, in serve_forever\n",
      "    self._stop_event.wait()\n",
      "  File \"src/gevent/event.py\", line 164, in gevent._gevent_cevent.Event.wait\n",
      "  File \"src/gevent/_abstract_linkable.py\", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait\n",
      "  File \"src/gevent/_abstract_linkable.py\", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core\n",
      "  File \"src/gevent/_abstract_linkable.py\", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core\n",
      "  File \"src/gevent/_abstract_linkable.py\", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified\n",
      "  File \"src/gevent/_abstract_linkable.py\", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub\n",
      "  File \"src/gevent/_greenlet_primitives.py\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\n",
      "  File \"src/gevent/_greenlet_primitives.py\", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\n",
      "  File \"src/gevent/_gevent_c_greenlet_primitives.pxd\", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "! python3 app.py\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
